from os.path import join
from shutil import rmtree
import sublime

package_name = 'AutoMatlab'

def plugin_unloaded():
    from package_control import events

    # just before removing
    if events.remove(package_name):
        # query user to remove all AutoMatlab data
        answer = sublime.ok_cancel_dialog('Removing AutoMatlab...\n\n'
            'Do you also want to remove all data generated by AutoMatlab?', 
            'Remove')

        if answer:
            try:
                # remove AutoMatlab from Packages folder
                auto_matlab_path = join(sublime.packages_path(), 'AutoMatlab')
                rmtree(auto_matlab_path)
            except:
                pass
